### ISSUE TITLE
[staging] "Run" title in single dataset page should be in blue and clickable for sorting

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#166] opened 2023-11-22 21:35 UTC
According to designs, "Run" title in single dataset page should be in blue and clickable for sorting

**Steps to Reproduce**
1. Click on Browse all data menu
2. Click on any Dataset
3. Navigate to Runs table
4. Pay attention to "Run" and compare to design

**Actual Results**
"Run" is in grey and not clickable

**Expected Results**
"Run" should be in blue and clickable for sorting

**Design**

<img width="825" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/b1c7f997-05c9-4c1e-a592-0b2d1696515f">

**Evidence**

https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/b0c44d11-40eb-4bbe-972e-500ec0ce17db

**Comment by Janeece** [comment] 2023-12-18 18:26
not a bug, sorting functionality was deprioritized for phase 2 implementation. Perhaps a backlog refinement or a future functionality? (cc @junxini )

**Comment by junxini** [comment] 2024-02-02 18:42
sorry i somehow just saw this. that's right it was deprioritized, we can resurface this as needed. will close this bug

**Closed by junxini** 2024-02-02 18:42 UTC
Labels: bug, website, frontend, severity - low
