### ISSUE TITLE
[staging] links are missing in "Sample and Experiment Conditions Optional subtitle" section in right panel

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#150] opened 2023-11-15 18:05 UTC
Organism Name, Tissue Name, Cell Name and Cell Line or Strain Name fields are missing their links

**Steps to Reproduce**

1. Click on <More info> button
2. Locate "Sample and Experiment Conditions Optional subtitle" section in right panel
3. Pay attention to Organism Name, Tissue Name, Cell Name and Cell Line or Strain Name fields
4. Compare to design

**Actual Results**
info in links are not included as links

**Expected Results**
info for these links should be marked as links

**Design**

<img width="502" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/17bb4bc4-92c0-4bef-af2b-1027aa961fe6">

**Evidence**

<img width="494" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/9b6678cc-e7c8-482e-ac30-039352e750c2">

**Comment by junxini** [comment] 2023-12-18 21:42
@Janeece to add in link examples that are taken from the metadata field. cc @jgadling

**Comment by Janeece** [comment] 2023-12-18 21:57
these fields use their respective ID's (not surfaced) to like to relevant external reference page in a new tab. 
@jgadling can you confirm if these are accurate designations/metadata?

- Organism Name link to NCBI Taxonomy entry. Based on "Taxonomy ID" metadata field. Example page: https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=4896&lvl=3&lin=f&keep=1&srchmode=1&unlock 

- Tissue Name link to UBERON. Based on "Tissue ID" metadata field. Example page: https://www.ebi.ac.uk/ols4/ontologies/bto/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBTO_0005765?lang=en

- Cell Name link to Cell Ontology. Based on "Cell type ID" metadata field. Example Page: https://www.ebi.ac.uk/ols4/ontologies/cl/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCL_0000540

- Cell Line/Strain link to NCBI. Based on "Cell Line ID" metadata field. Example page: https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=284812

**Comment by uermel** [comment] 2024-01-19 01:26
Link formats:

**Organism Name:** 
```python
f"https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id={Dataset.organism_taxid}"
```

**Tissue Name:**
```python
f"http://purl.obolibrary.org/obo/{Dataset.tissue_id.replace(":", "_")}"
```

**Cell Name**
```python
f"http://purl.obolibrary.org/obo/{Dataset.cell_type_id.replace(":", "_")}"
```

**Cell Line/Strain**
```python
f"https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id={Dataset.cell_strain_id}"
```

At @manasaV3's suggestion:

**Cellular component**
```python
f"http://purl.obolibrary.org/obo/{Dataset.cell_component_id.replace(":", "_")}"
```

**Comment by junxini** [comment] 2024-02-02 18:16
@lauramarcos i think this is fixed, could you help retest?

**Comment by lauramarcos** [comment] 2024-02-14 20:37
Working now as expected, closing this one, thank you!

**Comment by lauramarcos** [comment] 2024-02-22 20:39
Reopening as this is happening again, links are missing in Locate Sample and Experiment Conditions section

<img width="461" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/f616c3aa-4686-4d95-b0ec-9d8eba75fccf">

**Comment by junxini** [comment] 2024-05-07 01:15
ticket was reopened but wasn't move out of the "completed" column from portal bugs and fell through the cracks!

**Comment by kne42** [comment] 2024-05-07 17:39
on the frontend this is working as intended since if we are not given the respective ids we cannot create the links

@uermel are these supposed to have their ids all filled out on the backend?

**Comment by uermel** [comment] 2024-05-08 00:35
No, it's not necessarily expected for all fields to be filled. This depends on the `sample_type` and on whether the strain has an associated linkable source. In this example, since the `sample_type` is `cell` there won't be information for the `tissue` field, and I don't think we have an associated link for the strain.

**Comment by junxini** [comment] 2024-05-08 18:09
@uermel @lauramarcos closing this since not all of the organism fields have links. Please reopen if you think there is a link and it's not showing

**Closed by junxini** 2024-05-08 18:09 UTC
Labels: bug, website, frontend, severity - medium
