### ISSUE TITLE
Introduce annotation filters for single dataset

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/cryoet-data-portal#486] opened 2024-02-20 23:32 UTC
**Tasks**:

Add filters to narrow down runs by filtering on annotations.

**Link to design:**  https://www.figma.com/file/q6Z394Xy6wUmaXQ9YFjZH7/Kevin---2023-Spillover-Work?type=design&node-id=2118-11276&mode=design&t=41b8zGhU4oUzctHN-0

**Comment by manasaV3** [comment] 2024-02-20 23:33
Relates to #34

**Comment by junxini** [comment] 2024-02-21 18:40
duplicate of #488

**Comment by junxini** [comment] 2024-02-21 18:40
duplicate of #488

**Closed by junxini** 2024-02-21 18:40 UTC
Labels: P0, frontend
