### ISSUE TITLE
Clarify current search capabilities on all datasets page

### ISSUE THREAD

**Issue by kandarpksk** [chanzuckerberg/cryoet-data-portal#1052] opened 2024-08-20 23:57 UTC
Utz mentioned that users don't realize that the search function currently only looks up dataset titles. We should clarify that (while more elaborate search features are yet to be prioritized for Q4) by one of these means:
- Preferred: update hint text to say something like "Search dataset by title"
- Alternative: add a tooltip explaining that only dataset titles are searched currently, not other metadata

**Comment by junxini** [comment] 2024-08-21 20:47
I also like the first option of having hint text. tagging @dgmccart to help with wording recommendations

**Comment by dgmccart** [comment] 2024-08-21 20:55
I agree with Jun about preferring the hint text, and I think "Search datasets by title" is appropriate.

**Comment by junxini** [comment] 2024-10-31 16:51
duplicate of #1267

**Closed by junxini** 2024-10-31 16:51 UTC
Labels: documentation, P0, frontend, adhoc
