### ISSUE TITLE
Placeholder Value for Available Spacings under Single Run

### ISSUE THREAD

**Issue by kne42** [chanzuckerberg/cryoet-data-portal#482] opened 2024-02-20 19:46 UTC
https://github.com/chanzuckerberg/cryoet-data-portal/blob/498e4e02af55e01e9a3d70eca625931d19977eee/frontend/packages/data-portal/app/components/Run/RunHeader.tsx#L164

**Comment by manasaV3** [comment] 2024-02-22 23:05
Duplicate of https://github.com/chanzuckerberg/cryoet-data-portal/issues/394

**Closed by manasaV3** 2024-02-22 23:05 UTC
