### ISSUE TITLE
Estimated Download File Size for Zarr format

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#445] opened 2024-02-05 20:04 UTC
When downloading zarr format, show the download size in the download dialog labeled "Estimated Download Size". 

This is related to #360 - except this ticket is specific for Zarr since it takes additional backend computation to get to the size information

**Comment by manasaV3** [comment] 2024-03-04 22:03
Closed as duplicate of https://github.com/chanzuckerberg/cryoet-data-portal/issues/444

**Closed by manasaV3** 2024-03-04 22:03 UTC
Labels: P1, backend, frontend
