### ISSUE TITLE
[staging] "Size (x, y, z)" is not considered part of "Smallest Available Voxel Spacing" in right panel for Single Run Page

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#251] opened 2023-12-12 18:47 UTC
**Steps to Reproduce**
1. Click on a run
2. Click on "More Info" button / link
3. Locate Tomograms section
4. Compare to design

**Actual Results**
"Size (x, y, z)" is not considered part of "Smallest Available Voxel Spacing"

**Expected Results**
"Size (x, y, z)" is part of "Smallest Available Voxel Spacing" according to design

**Design**
<img width="637" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/a32f28d5-b0b9-43f8-8e9d-c45e5fe98b95">

**Evidence**

<img width="460" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/0e1a7fce-b044-4b19-af6f-ba6c2e329c3e">

**Comment by Janeece** [comment] 2023-12-18 18:49
not a bug - this style change fell OOS. I think this should be a backlog refinement/ part of the work to refine metadata tables in H1 (cc @junxini )

**Comment by junxini** [comment] 2023-12-18 19:14
thanks @lauramarcos for raising this. Agree @Janeece, will close this as it fell out of scope and add it to H1 work

**Closed** 2023-12-18 19:14 UTC
Labels: bug, website, frontend
