### ISSUE TITLE
[staging] Tools dropdown menu shows up on left side after clicking on it several times

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#153] opened 2023-11-15 19:18 UTC
**Steps to Reproduce**

1. Click on Tools menu to open dropdown
2. Click on Tools again to close dropdown
3. Click on Tools again
4. Click outside dropdown
5. Continue this process until dropdown shows up on left side

**Actual Results**
Dropdown is displayed on left side corner of scree

**Expected Results**
Dropdown should always be displayed under menu

**Evidence**

https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/35f020f3-daa2-4f8d-be75-3c6bc936776a

**Comment by junxini** [comment] 2023-12-08 23:33
@lauramarcos closing this as it's a duplicate of #115

**Comment by junxini** [comment] 2023-12-08 23:34
@lauramarcos closing this as it's a duplicate of #115

**Closed** 2023-12-08 23:34 UTC
Labels: bug, website, frontend
