### ISSUE TITLE
[staging] About & Help menu not closing when navigating thru it

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#246] opened 2023-12-11 23:50 UTC
**Steps to Reproduce**
1. Click on About & Help menu
2. Navigate thru menu

**Actual Results**
Menu dropdown not closing when clicking on any option in menu

**Expected Results**
Menu dropdown should close when clicking on any option in menu

**Evidence**

https://github.com/chanzuckerberg/cryoet-data-portal/assets/63799148/43aa438d-1cf8-4788-a3ff-37138b0b209c

**Comment by junxini** [comment] 2024-04-17 18:37
duplicate of #493

**Closed by junxini** 2024-04-17 18:37 UTC
Labels: bug, website, frontend, severity - low
